version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - "7979:7979"
      - "5000:5000"
    volumes:
      - ../back_end:/opt/dobie-server
    depends_on:
      - database
    entrypoint: python -u /opt/dobie-server/main.py


  database:
    container_name: database
    build:
      context: database
    volumes:
      - database-volume:/var/lib/mysql

  webserver:
    container_name: webserver
    build:
      context: webserver
    ports:
      - "80:80"
    volumes:
      - ../front_end:/site
    depends_on:
      - php


  php:
    container_name: php
    build:
      context: php
    volumes:
      - ../front_end:/site


  nodejs:
    container_name: nodejs
    build:
      context: nodejs
    ports:
      - "5002:5002"
      - "5004:5004"
    volumes:
      - ../front_end:/site
    entrypoint: sh run-events-live.sh



volumes:
    database-volume:


