version: '3.7'

services:

  backend:
    image: "dobie/${IMG_PRFX}backend:latest"
    container_name: backend
    ports:
      - "9797:9797"
      - "5000:5000"
    volumes:
      - ../back_end:/opt/dobie-server
      - ../certs/ctrller_connection:/var/lib/dobie-certs
      - /var/log/dobie-s:/var/log/dobie-s
      - /var/lib/dobie-pers-imgs:/var/lib/dobie-pers-imgs
    networks:
      - dobie-net
    depends_on:
      - database
    command: python -u /opt/dobie-server/main.py
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"


  database:
    image: "dobie/${IMG_PRFX}database:latest"
    container_name: database
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - dobie-net
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"


  webserver:
    image: "dobie/${IMG_PRFX}webserver:latest"
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../front_end:/site
      - ../certs/https:/etc/nginx/ssl
    networks:
      - dobie-net
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"



  php:
    image: "dobie/${IMG_PRFX}php:latest"
    container_name: php
    build:
      context: "${IMG_PRFX}php"
    volumes:
      - ../front_end:/site
    networks:
      - dobie-net
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"


  nodejs:
    image: "dobie/${IMG_PRFX}nodejs:latest"
    container_name: nodejs
    ports:
      - "5002:5002"
      - "5004:5004"
    volumes:
      - ../front_end:/site
      - ../certs/https:/certs
    networks:
      - dobie-net
    entrypoint: sh run-events-live.sh
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"




volumes:
  database-volume:



networks:
  dobie-net:
