version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - "7979:7979"
      - "5000:5000"
    volumes:
      - ../back_end:/opt/dobie-server
      - /var/log/dobie-s:/var/log/dobie-s
      - /var/lib/dobie-pers-imgs/:/var/lib/dobie-pers-imgs
    depends_on:
      - database
    entrypoint: python -u /opt/dobie-server/main.py
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"


  database:
    container_name: database
    build:
      context: database
    volumes:
      - database-volume:/var/lib/mysql

  webserver:
    container_name: webserver
    build:
      context: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../front_end:/site
      - ../certs:/etc/nginx/ssl/
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"



  php:
    container_name: php
    build:
      context: php
    volumes:
      - ../front_end:/site
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"


  nodejs:
    container_name: nodejs
    build:
      context: nodejs
    ports:
      - "5002:5002"
      - "5004:5004"
    volumes:
      - ../front_end:/site
      - ../certs:/certs
    entrypoint: sh run-events-live.sh
    logging:
      driver: "json-file"
      options:
        max-size: "7m"
        max-file: "7"



volumes:
    database-volume:


