version: '3.3'

services:
  nginx:
    container_name: webserver
    build:
      context: webserver
    ports:
      - "80:80"
    volumes:
      - ../front_end:/site
    links:
      - php
    depends_on:
      - php

  php:
    image: php:7-fpm-alpine
    container_name: php
    volumes:
      - ../front_end:/site

