import logging

LOGGING_FILE ='server.log'

BIND_IP = '0.0.0.0'
BIND_PORT = 7979
SOCK_BUF_LEN = 32768
SIM_DEV_CONNECTIONS = 500
RECV_TIMEOUT = 2

MGT_BIND_IP = '0.0.0.0'
MGT_BIND_PORT = 4441
MGT_SOCK_BUF_LEN = 512
MGT_SIM_DEV_CONNECTIONS = 100

DEFAULT_SEND_RETRIES = 7
DEFAULT_TIME_WAIT_RESPONSE = 10

EXIT_CHECK_TIME = 2
KEEP_ALIVE_TIME = 6

loggingLevel = logging.DEBUG



