#!/bin/bash


echo "Dobie Server Installation Script"
echo "================================"

echo "Creating directory for Dobie Server Logs.."
sudo mkdir -p /var/log/dobie-s/

read -p "Do you want to set log rotation for Dobie Server (y/n): " answer
if [ $answer == y ] || [ $answer == Y ]; then
cat > /tmp/dobie-s.logrotate << EOL
/var/log/dobie-s/dobie-s.log
{
    daily
    missingok
    rotate 10
    notifempty
}
EOL

sudo cp /tmp/dobie-s.logrotate /etc/logrotate.d/dobie-s
sudo rm /tmp/dobie-s.logrotate

fi

read -p "Are you installing Dobie Server in the same controller (y/n): " answer
#Change to the directory where the docker-compose.yml file is located and
#save the complete path of the directory in the variable DOCK_COMP_DIR to
#be able to create then the systemd unit to start all the containers
if [ $answer == y ] || [ $answer == Y ]; then
  cd ../ctrller_docker/
  DOCK_COMP_DIR=$(realpath .)
else
  cd ../docker/
  DOCK_COMP_DIR=$(realpath .)
fi

#Building the containers without starting them
echo "Building Docker containers.."
docker-compose -p dobie up --no-start

echo "Setting Dobie Server as Systemd service.."
cat > /tmp/dobie-s.service << EOL
[Unit]
Description=Docker Compose Dobie Containers
After=docker.service network-online.target
Requires=docker.service network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes

ExecStart=/usr/bin/docker-compose -p dobie -f $DOCK_COMP_DIR/docker-compose.yml start
ExecStop=/usr/bin/docker-compose -p dobie -f $DOCK_COMP_DIR/docker-compose.yml stop


[Install]
WantedBy=multi-user.target
EOL
sudo cp /tmp/dobie-s.service /etc/systemd/system/
sudo rm /tmp/dobie-s.service

sudo systemctl daemon-reload

read -p "Do you want to start Dobie Server at boot time (y/n): " answer
if [ $answer == y ] || [ $answer == Y ]; then
  sudo systemctl enable dobie-s.service
fi

#Now starting all the containers using the previously created unit
echo "Starting Dobie server (all the containers).."
sudo systemctl start dobie-s.service


#If there is any previous DB, reset it
echo "Erasing any previous database and setting initial values to it.."
cd ../scripts/
docker stop backend > /dev/null 2>&1
./db-create-drop.sh -r 
docker start backend > /dev/null 2>&1


#Every day at 07:07:07 the purge-old-events.sh is run receiving 
#the amount of months to keep in DB.
#To do this, a systemd timer is created.
read -p "How many months of events do you want to store in Database: " MONTH
cat > /tmp/purge-dobie-db.service << EOL
[Unit]
Description=Purge old events of Dobie DB

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c '$(realpath purge-old-events.sh) $MONTH'
EOL
sudo cp /tmp/purge-dobie-db.service /etc/systemd/system/
sudo rm /tmp/purge-dobie-db.service 

cat > /tmp/purge-dobie-db.timer << EOL
[Unit]
Description=Weekly purge old events of Dobie DB

[Timer]
OnCalendar=*-*-* 07:07:07

[Install]
WantedBy=timers.target
EOL
sudo cp /tmp/purge-dobie-db.timer /etc/systemd/system/
sudo rm /tmp/purge-dobie-db.timer

sudo systemctl daemon-reload
sudo systemctl enable purge-dobie-db.timer
sudo systemctl start purge-dobie-db.timer


#The following scripts are used to save and restore the DB at any moment.
#They should be executed by the user.
#The script which restores the database, receives the file generated by the
#script which saves the database, as an argument.
#This script stops the backend before restoring the DB to avoid freezing
#in some cases. 
echo "Installing scripts to save and restore Dobie DB.."
cat > /tmp/dobie-save-db << EOL
#!/bin/bash

. $(realpath db-config)

DB_DOCKER_IP=\$(tr -d '", ' <<< \$(docker inspect database | grep '"IPAddress": "1' | gawk '{print \$2}'))

mysqldump -u \$DB_USER -p\$DB_PASSWD -h \$DB_DOCKER_IP \$DB_DATABASE > dobie_db_\$(date +%F_%H:%M).dump
EOL
sudo cp /tmp/dobie-save-db /usr/local/sbin/dobie-save-db
sudo rm /tmp/dobie-save-db
sudo chmod +x /usr/local/sbin/dobie-save-db


cat > /tmp/dobie-restore-db << EOL
#!/bin/bash

. $(realpath db-config)

DB_DOCKER_IP=\$(tr -d '", ' <<< \$(docker inspect database | grep '"IPAddress": "1' | gawk '{print \$2}'))

echo "Stopping Backend.."
docker stop backend

echo "Restoring DB.."
mysql -u \$DB_USER -p\$DB_PASSWD -h \$DB_DOCKER_IP \$DB_DATABASE < \$1

echo "Starting Backend.."
docker start backend
EOL
sudo cp /tmp/dobie-restore-db /usr/local/sbin/dobie-restore-db
sudo rm /tmp/dobie-restore-db
sudo chmod +x /usr/local/sbin/dobie-restore-db



